name: Deploy Grafana ECS

on:
  push:
    branches:
      - marquez

jobs:
  terraform:
    name: Terraform Apply
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        working-directory: ./env/marquez
        run: terraform init

      - name: Terraform Validate
        working-directory: ./env/marquez
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./env/marquez
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./env/marquez
        run: terraform apply -auto-approve tfplan
