name: Deploy Marquez ECS

on:
  push:
    branches:
      - marquez_single

jobs:
  terraform:
    name: Terraform Apply
    runs-on: self-hosted

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: ğŸ§± Terraform Init
        working-directory: ./env/marquez
        run: terraform init

      - name: âœ… Terraform Validate
        working-directory: ./env/marquez
        run: terraform validate

      - name: ğŸ“ Terraform Plan
        working-directory: ./env/marquez
        run: terraform plan -out=tfplan

      - name: ğŸš€ Terraform Apply
        working-directory: ./env/marquez
        run: terraform apply -auto-approve tfplan
